cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    anna:
      email: anna.gunaza@schroeck-consulting.de
      failed_login_attempts: 0
      first_name: anna
      last_name: gunaza
      logged_in: false
      password: $2b$12$SJAmmlGCWOnX8vknrv.la.tSm1z2OsH2yQ0AtepmdgECND6YQnGOK
      password_hint: hint
      roles: null
oauth2:
  google:
    client_id: null
    client_secret: null
    redirect_uri: null
  microsoft:
    client_id: null
    client_secret: null
    redirect_uri: null
    tenant_id: null
pre-authorized:
  emails:
  - anna.gunaza@schroeck-consulting.de
  - dominik@schroeck-consulting.de
